### ISSUE TITLE
A non-object value where an object is expected throws an error

### ISSUE THREAD

**Issue by Hainesy** [typestack/class-validator#515] opened 2020-01-30 10:18 UTC
When the `ValidatedNested` and `Type` decorators are used on a property, but the property contains a non-object value, e.g. a string or number, the code throws an error `Cannot read property 'map' of undefined` from the recursive `getErrors` function.

**Comment by weihanchen** [comment] 2020-02-11 00:48
I have the same issue

**Comment by vlapo** [comment] 2020-03-16 21:05
Duplicate of https://github.com/typestack/class-validator/issues/193

**Closed by vlapo** 2020-03-16 21:05 UTC
