### ISSUE TITLE
fix: IsBooleanTrue property to check if user checked the checkbox

### ISSUE THREAD

**Issue by abhimanusharma** [typestack/class-validator#1106] opened 2021-06-02 03:28 UTC
I have tried using IsBoolean, IsBooleanString, IsEmpty and IsNotEmpty property but they all are passing the validation. Is there a way to check the validation of a boolean is checked?

**Comment by NoNameProvided** [comment] 2022-12-09 20:03
Closing as cannot reproduce. No minimal reproducible example as provided.

**Closed by NoNameProvided** 2022-12-09 20:03 UTC
Labels: type: fix, status: cannot reproduce
