### ISSUE TITLE
feature: generate schema from class

### ISSUE THREAD

**Issue by christophmayrhofer** [typestack/class-validator#140] opened 2017-11-27 21:12 UTC
I see that it is possible to use a json schema to validate against.
Is it also possible to generate the schema from the class?

I am currently using simpl-schema which has a great ecosystem (e,g, auto generating forms)
However, I want to move away from json based schemas towards a more modern approach (i.e. class-validator package), but now I would need to define everything twice (decorators & json schema). 
Generating the schema from decorators would prevent a lot of duplicate code.

I don't really care about the syntax/structure of the generated json schema since I can just write a transformer to generate the simpl-schema syntax from it.

I also don't mind contributing if you can point me into the right direction. I would need some way to get all validator types and their arguments:

```
schema = {}
properties.forEach(property => {
    property.validators.forEach(validator => {
            schema[property.name][validator.name] = validator.value
    })
})
```

**Comment by christophmayrhofer** [comment] 2017-11-28 13:20
Ok, I have figured out how to get the metadata and I can generate the schema.
Now I am stuck at nested Validations. Can I somehow access the nested metadata as well?

bookSchema = {
title{isString: true},
pages: {max: 1000, min: 0, isInt: true},
author: {nestedValidation: true}
}

schema() {
        let container = (<MetadataStorage>getFromContainer(MetadataStorage))
        let metadata = container.getTargetValidationMetadatas(this.constructor, JSON.stringify(this))
        let properties = container.groupByPropertyName(metadata)

        let schema = Object.keys(properties).reduce((schema, property) => {
            schema[property] = properties[property].reduce((propertySchema, {type, constraints}) => {
                if (Array.isArray(constraints) && constraints.length === 1)
                    constraints = constraints[0]
                if (typeof constraints === "undefined")
                    propertySchema[type] = true
                else
                    propertySchema[type] = constraints
                return propertySchema
            }, {})
            return schema
        }, {})
        return schema
    }

**Comment by breath103** [comment] 2018-01-09 08:49
is there any progress on this? it would be really nice to have this feature.

**Comment by NoNameProvided** [comment] 2018-03-17 17:28
Related #5, #129

**Comment by braaar** [comment] 2022-11-16 20:06
Closing as duplicate of #5. 

Note that schema-based validation is deprecated.

**Closed by braaar** 2022-11-16 20:06 UTC
Labels: type: feature, status: wontfix, flag: schema-based-validation
