### ISSUE TITLE
GooglePhoneLib overhead is extreme

### ISSUE THREAD

**Issue by porschuetz** [typestack/class-validator#410] opened 2019-08-21 10:19 UTC
I would like to recommend to be using a different library or make this dependency optional.

For example:
https://github.com/catamphetamine/libphonenumber-js
is a solid rewrite with a significant size reduction.

I don't use the phone number validator at all, but I would have to fork class-validator to reduce my package size dramatically. See my package analysis:

![Screenshot 2019-08-21 at 12 15 57](https://user-images.githubusercontent.com/1228101/63424064-e65d3d80-c40d-11e9-9267-645a6ba471cd.png)

**Comment by stepanh** [comment] 2019-08-21 23:27
Yes, this is gigantic.
I'd actually like to exclude class-validator from my frontend bundle altogether and only use it on the backend. Is there something like [typeorm-model-shim](https://github.com/typeorm/typeorm/blob/master/extra/typeorm-model-shim.js) for class-validator?

**Comment by vlapo** [comment] 2019-08-22 18:04
Duplicate of https://github.com/typestack/class-validator/issues/248. I am working on it Please be patient.

**Closed by vlapo** 2019-08-22 18:04 UTC

**Comment by jbjhjm** [comment] 2019-08-26 13:32
@porschuetz @stepanh If you didn't see, Djaler posted a workaround for everyone using webpack:
https://github.com/typestack/class-validator/pull/258#issuecomment-521587401
