### ISSUE TITLE
Error "Validation.js Error: This library (validator.js) validates strings only" on number field

### ISSUE THREAD

**Issue by fabiobeoni** [typestack/class-validator#70] opened 2017-02-23 13:21 UTC
Hello,

I'm getting this error on a number field on my class:

**Some model class...**

```ts
@IsIn([
      Difficulties.EASY,
      Difficulties.MEDIUM,
      Difficulties.DIFFICULT
    ])
    public difficulty:number;
```

```ts
export class Difficulties {
  static EASY:number=0;
  static MEDIUM:number=1;
  static DIFFICULT:number=2;
};
```

According to this post looks like the validator.js library doesn't work anymore with fields that are not STRING: https://github.com/chriso/validator.js/issues/505

Thanks, F.

**Comment by bismert** [comment] 2017-08-09 12:53
I am facing similar problem as @fabiobeoni

**Comment by NoNameProvided** [comment] 2018-01-08 07:54
Hi @fabiobeoni! 

I am going to close this as I cannot reproduce this issue with the current release.

```ts
import { IsIn, validate } from 'class-validator';

export class Difficulties {
  static EASY: number = 0;
  static MEDIUM: number = 1;
  static DIFFICULT: number = 2;
};

export class TestClass {
  @IsIn([
    Difficulties.EASY,
    Difficulties.MEDIUM,
    Difficulties.DIFFICULT
  ])
  public difficulty: number;
}

const instance = new TestClass()
instance.difficulty = 9

validate(instance).then(console.log);
```

This will return with the correct error: 

```
difficulty must be one of the following values: 0,1,2
```

**Closed by NoNameProvided** 2018-01-08 07:54 UTC
