### ISSUE TITLE
question: ability to disable all other validations if type validation fails

### ISSUE THREAD

**Issue by bogdan** [typestack/class-validator#667] opened 2020-08-03 13:24 UTC
Type validation is a core thing when data is validated when received via API e.g in JSON format.

**I was trying to...** disable all other validations when a property doesn't pass type validation. 

Example:

``` typescript
import {
  IsString,
  validate,
  IsInt,
  Min,
} from 'class-validator';

class A {
  @IsInt()
  @Min(10)
  a: number
}

const val = new A();
a.a = '112' as any;
validate(a) /* =>  [
  ValidationError {
    target: A { a: '112' },
    value: '112',
    property: 'a',
    children: [],
    constraints: {
      min: 'a must not be less than 2',
      isInt: 'a must be an integer number'
    }
  }
]
*/
```

Ideally, I want only `isInt` error to appear but not `min` error.

### The problem

`@IsInt` validator failure doesn't stop any other validator from being run even though other validations are pretty irrelevant when type validation fails. I see it as pattern for any task I have.

Is it possible to make type validators behave in the same way as `IsDefined` validator that stops any further validator from being run?

### The Solution 

I believe that a special behavior of `IsDefined` validator should be an exposed option like `@IsInt({absolute: true})` that would cause every other validator to be ignored when this one fails.
But I am open to other proposals.

**Comment by NoNameProvided** [comment] 2020-08-04 21:46
The requested functionality is the duplicate of #188.

**Closed** 2020-08-04 21:46 UTC
Labels: status: duplicate
