### ISSUE TITLE
Mock the decorators

### ISSUE THREAD

**Issue by jannomeister** [typestack/class-validator#557] opened 2020-03-20 04:20 UTC
First of all, this library is so awesome! I used it to automatically validate the incoming data from the client to my controllers (btw I'm using `NestJS`). But in my e2e testing how can I mock the class-validator using jest?

**Comment by vlapo** [comment] 2020-03-24 20:15
Duplicate of https://github.com/typestack/class-validator/issues/494. Sorry I do not have answer for you now.

**Closed by vlapo** 2020-03-24 20:15 UTC
