### ISSUE TITLE
fix: `@IsDateString` and `@IsIso8601` decorators do not validate dates in 'yyyy-MM-dd' format

### ISSUE THREAD

**Issue by fselcukcan** [typestack/class-validator#923] opened 2021-02-19 15:53 UTC
I use `IsDateString` or `IsIso8601` and they do not let a '`yyyy-MM-dd`' pass. hey complain the string must be ISO date string. Is not a `'yyyy-MM-dd'` format valdi in that case? Is a date like `'2010-12-01'` a valid `'yyyy-MM-dd'` or iso 8601 date string. According to here it is: https://en.wikipedia.org/wiki/ISO_8601.

**Comment by NoNameProvided** [comment] 2022-12-09 21:48
It validates the `YYYY-MM-DD` format correctly. From my comment in https://github.com/typestack/class-validator/issues/387#issuecomment-1344771356: 

This is currently possible. The `@IsDateString` can validate only `YYYY-MM-DD` pattern, and with a `@MaxLenght` decorator you can enforce that no time part is specified. 

```ts
import { IsDateString, MaxLength, validate } from 'class-validator';

class MyPayload {
  @MaxLength(10)
  @IsDateString()
  date: string;

  constructor(date?: string) {
    this.date = date;
  }
}

// Will pass
validate(new MyPayload('2022-12-24')).then(console.log);
// Will fail
validate(new MyPayload('2022-12-24:12:00:00Z')).then(console.log);
validate(new MyPayload('invalid')).then(console.log);
```

**It's always a good idea to think of decorators as pieces of Lego.** Some things can only be achieved with multiple decorators. The solution is not always to extend the decorator we first thought of using to match my exact use-case. 

Closing as cannot reproduce.

**Closed by NoNameProvided** 2022-12-09 21:48 UTC
Labels: type: fix, status: duplicate
