### ISSUE TITLE
Excluding google-libphonenumber

### ISSUE THREAD

**Issue by binaryangel-noa** [typestack/class-validator#472] opened 2019-11-21 13:36 UTC
Google libphonumber is a large depdendency of the class-valdiator package (450KB vs 50KB of class-valdiator). Is there an option to use it optionally ?

**Comment by rubiin** [comment] 2019-11-21 17:47
i dont think you can use it optionally or may be i am wrong, perhaps @vlapo  can tell you more

**Comment by vlapo** [comment] 2019-11-26 15:38
Sorry there is such option.

**Comment by alex-nishikawa** [comment] 2019-12-19 09:33
Does this library support just using the modules you want?  Example: 
`
import length from 'class-validator/length`
`

**Comment by vlapo** [comment] 2020-01-10 12:23
No this library do not support tree shaking and modules yet.

**Comment by AndrinGautschi** [comment] 2020-02-20 15:50
Is someone working on this issue?

**Comment by vlapo** [comment] 2020-03-27 21:34
Duplicate of https://github.com/typestack/class-validator/issues/248

**Closed by vlapo** 2020-03-27 21:34 UTC
Labels: type: question
