### ISSUE TITLE
Is there a way to use "or" logic 

### ISSUE THREAD

**Issue by veryaskinan** [typestack/class-validator#558] opened 2020-03-22 13:13 UTC
For example, I want my field to be integer or string. Can I use something like:
```
@IsInt() or @isString
```
?

**Comment by ZBAGI** [comment] 2020-03-24 18:21
You can create custom validator that will handle this case:
```typescript
import {registerDecorator, ValidationOptions, ValidationArguments} from "class-validator";

export function IntOrString(property: string, validationOptions?: ValidationOptions) {
   return function (object: Object, propertyName: string) {
        registerDecorator({
            name: "intOrString",
            target: object.constructor,
            propertyName: propertyName,
            options: validationOptions,
            validator: {
                validate(value: any, args: ValidationArguments) {
                    const validator = new classValidator();
                    return validator.isInt(value) || validator.isString(value);
                },
                defaultMessage(validationArguments?: ValidationArguments) {
                    return "Has to be int or string";
                }
            }
        });
   };
}
```

**Comment by ZBAGI** [comment] 2020-03-24 18:23
You can create custom validator that will handle this case:
```typescript
import {registerDecorator, ValidationOptions, ValidationArguments, Validator} from "class-validator";

export function IntOrString(property: string, validationOptions?: ValidationOptions) {
   return function (object: Object, propertyName: string) {
        registerDecorator({
            name: "intOrString",
            target: object.constructor,
            propertyName: propertyName,
            options: validationOptions,
            validator: {
                validate(value: any, args: ValidationArguments) {
                    const validator = new Validator();
                    return validator.isInt(value) || validator.isString(value);
                },
                defaultMessage(validationArguments?: ValidationArguments) {
                    return "Has to be int or string";
                }
            }
        });
   };
}
```

**Comment by vlapo** [comment] 2020-03-24 20:06
Duplicate of https://github.com/typestack/class-validator/issues/160. 

@ZBAGI thank you for your response.

**Closed by vlapo** 2020-03-24 20:06 UTC
