### ISSUE TITLE
Custom validators using schema 

### ISSUE THREAD

**Issue by aaleksandrov** [typestack/class-validator#473] opened 2019-11-22 08:56 UTC
Hi,
is it possible to create a custom validator and use it with validation schema? I don't want to use decorators because I don't control model (it comes from some sdk).
Please consider the following TS example. How should `customValidationSchema` look to make the custom validator work?

```
import {ValidatorConstraint, ValidatorConstraintInterface, ValidationArguments, ValidationSchema, registerSchema, validate} from 'class-validator';

@ValidatorConstraint({ name: 'customText', async: false })
export class CustomTextLength implements ValidatorConstraintInterface {

    validate(text: string, _args: ValidationArguments) {
        return text.length > 1 && text.length < 5;
    }

    defaultMessage(_args: ValidationArguments) {
        return 'Text ($value) is too short or too long!';
    }
}

class Model {
    name: string;
}

const instance = new Model();
instance.name = 'too-long-name-';

// This schema doesn't work
const customValidationSchema: ValidationSchema = {
    name: 'myCustomSchema',
    properties: {
        name: [{
            type: 'customValidation',
            constraints: [CustomTextLength]
        }],
    }
};

registerSchema(customValidationSchema);

validate('myCustomSchema', instance).then(errors => {
    if (errors.length > 0) {
        console.log('Validation failed: ', errors);
    } else {
        console.log('Validation succeed.');
    }
});

```

**Comment by vlapo** [comment] 2020-01-10 11:59
I dont think so `class-validator` support custtom validators. Also this feature is listed in 1.0 roadmap https://github.com/typestack/class-validator/issues/178.

Close as duplicate of https://github.com/typestack/class-validator/issues/186

**Comment by NoNameProvided** [comment] 2022-12-15 21:48
Schema validation is deprecated in the library. Closing this as wontfix.

**Closed by NoNameProvided** 2022-12-15 21:48 UTC
Labels: type: question, flag: schema-based-validation
