### ISSUE TITLE
error TS2503: Cannot find namespace 'ValidatorJS'.

### ISSUE THREAD

**Issue by Ayzrian** [typestack/class-validator#487] opened 2019-12-10 11:52 UTC
Hi.
I am writing a Nest application. And i am using class-validator. It fails on building phase with nex error.
 node_modules/class-validator/validation/Validator.d.ts:383:38 - error TS2503: Cannot find namespace 'ValidatorJS'.

I followed to that place and found next.

![image](https://user-images.githubusercontent.com/44115170/70527298-3f371a00-1b54-11ea-8426-4548a3b92a36.png)

**Comment by Ayzrian** [comment] 2019-12-10 12:09
Partly solve by changing modules files. I applied next changes.

1. Add import statement in file validator.ts

![image](https://user-images.githubusercontent.com/44115170/70528297-8e7e4a00-1b56-11ea-843b-b35f4e7e8943.png)

2. Change @types/validator module defenition on 

![image](https://user-images.githubusercontent.com/44115170/70528335-a05fed00-1b56-11ea-9fa5-48c4005961c0.png)

**Comment by cjancsar** [comment] 2019-12-10 20:28
There is already an open issue for this: https://github.com/typestack/class-validator/issues/468

**Comment by vlapo** [comment] 2020-01-10 12:11
Duplicate of #468

**Closed** 2020-05-05 18:00 UTC
