### ISSUE TITLE
fix: validation fails when using `forbidUnknownValues`

### ISSUE THREAD

**Issue by Thomas-1985** [typestack/class-validator#1474] opened 2022-01-02 15:21 UTC
### Description

```
      "class-transformer": "^0.3.1",
      "class-transformer-validator": "^0.9.1",
      "class-validator": "^0.12.1",
```

I have an issue if i set  `forbidUnknownValues` in my validator config. I am trying to validate a configuration which comes from a .json file

**Minimal code-snippet showcasing the problem**

My validation class looks like this.
```
export class SystemConfigs {
  deployment: DeploymentConfig
  db: DBConfig
  general: GeneralConfig
  builtinStreaming: StreamingConfig
  localization: LocalizationConfig
  mailing: MailConfig
  hotkeys: HotkeysConfig
  version: VersionConfig
  features: FeaturesConfig
  currencies: CurrenciesConfig
  defaults: DefaultsConfig
}
```

All sub configs are implemented to validate successfully i.e.
```
export class VersionConfig {
  @IsNotEmpty()
  @IsNumber()
  @IsPositive()
  config: number
}
```

The function to load and validate the config is 
```
  static async loadConfig(): Promise<boolean> {
    try {
      console.log("Loading config");
      const newSystemConfigString = fs.readFileSync(configFilePath, 'utf8');
      const newSystemConfig: SystemConfigs = JSON.parse(newSystemConfigString);

      const localOptions = {...VALIDATE_OPTIONS};
      localOptions.whitelist= true
      localOptions.forbidNonWhitelisted= true
      localOptions.forbidUnknownValues= false
      localOptions.validationError = {
        target: true,
        value: true
      };
      await transformAndValidate(SystemConfigs,newSystemConfigString, {validator: localOptions});
      console.log("Loading config succeeded");

      // Set config
      subsystems.configs = newSystemConfig;
      return true;
    } catch (errors) {
      if (errors.length > 0) {
        const errorArray: string[] = [];
        await ValidationService.traverseErrorTree(errors, errorArray, null);
        console.log("Loading config failed, errors are: ");
        for (const error of errorArray) {
          console.log(error);
        }
      }
      return false;
    }
  }
```

If i set `localOptions.forbidUnknownValues= false` i get the error "an unknown option was passed to the validator function"
If i set it to `false` i get
```
{"whitelistValidation":"property version should not exist"}
{"whitelistValidation":"property features should not exist"}
{"whitelistValidation":"property deployment should not exist"}
{"whitelistValidation":"property db should not exist"}
{"whitelistValidation":"property general should not exist"}
{"whitelistValidation":"property builtinStreaming should not exist"}
{"whitelistValidation":"property localization should not exist"}
{"whitelistValidation":"property mailing should not exist"}
{"whitelistValidation":"property hotkeys should not exist"}
{"whitelistValidation":"property currencies should not exist"}
{"whitelistValidation":"property defaults should not exist"}
```

The error is the same when i use `validateSync()`

What i want to achieve is

- All required values should be in the config, return an error otherwise
- If there are unknown values in the config (values not declared in the validation class), return an error

### Expected behavior
The validation should succeed without errors

### Actual behavior
The validations doesn't succeed

**Comment by Thomas-1985** [comment] 2022-01-15 00:51
Seems to work with this class and the same settings as above

```
export class SystemConfigs {
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => DeploymentConfig)
  deployment: DeploymentConfig

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => DBConfig)
  db: DBConfig

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => GeneralConfig)
  general: GeneralConfig

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => StreamingConfig)
  builtinStreaming: StreamingConfig

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => LocalizationConfig)
  localization: LocalizationConfig

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => MailConfig)
  mailing: MailConfig

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => HotkeysConfig)
  hotkeys: HotkeysConfig

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => VersionConfig)
  version: VersionConfig

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => FeaturesConfig)
  features: FeaturesConfig

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => CurrenciesConfig)
  currencies: CurrenciesConfig

  @IsNotEmpty()
  @ValidateNested()
  @Type(() => DefaultsConfig)
  defaults: DefaultsConfig
}
```

One thing i quite don't understand is why i have to provide the `@Type()`  of each subclass. I though, this its pulled from the definition, i.e.
```
  defaults: DefaultsConfig
```

**Comment by NoNameProvided** [comment] 2022-12-09 19:29
As mentioned in the docs, `class-validator` only operates on class instances at the moment.

Closing this as expired. If your problem still persists please open a new issue and provide a **reproducible and minimal** example. Your current example is not reproducible, because `transformAndValidate` is not included.

**Closed as completed by NoNameProvided** 2022-12-09 19:29 UTC
Labels: type: fix, status: invalid / expired
