### ISSUE TITLE
fix: IsIn decorator does not work if given a boolean

### ISSUE THREAD

**Issue by jithinlalpr** [typestack/class-validator#1066] opened 2021-05-07 07:16 UTC
### Description
Given the `IsIn` decorator for field validation. passed in a boolean value of `false` and the validator failed

```	@IsString()
	@IsIn(TASK_TYPE)
	public type: string;
```

### Expected behavior
A validation error should be thrown, stating that the string is not in the array mentioned

### Actual behavior
Simply pass the validation

**Comment by NoNameProvided** [comment] 2022-12-16 00:08
This is working as expected for me:
```ts
import { IsIn, validate } from 'class-validator';

class MyPayload {
  @IsIn(['a', 'b'])
  value?: string;

  constructor(value?: string) {
    this.value = value;
  }
}

// Will pass as expected
validate(new MyPayload('a')).then(console.log);
validate(new MyPayload('b')).then(console.log);

// Will fail as expected
validate(new MyPayload(true as any)).then(console.log);
validate(new MyPayload(false as any)).then(console.log);
validate(new MyPayload(undefined)).then(console.log);
validate(new MyPayload(null)).then(console.log);
```

Next time please provide a __minimal__ reproducible example showcasing your problem. The example should:

- be as short as possible while clearly showcasing the problem
- has no external dependencies, only this lib
- the expected and actual behavior should be explained

Closing as cannot reproduce.

**Closed** 2022-12-16 00:08 UTC
Labels: type: fix, status: cannot reproduce
