### ISSUE TITLE
feature: Transform decorator-based schema into json schema

### ISSUE THREAD

**Issue by steinroe** [typestack/class-validator#886] opened 2021-01-28 07:25 UTC
Hi, I am wondering whether it is possible to retrieve the JSON schema from a validation class defined by decorators. 

The use case is the following: In each service, I define the schema for the relevant entity in a class using class-validators decorators. Now, I want other services to access and use the same schema from that service. Hence, I would like to be able to request the schema via an API and then register it. Naturally, this requires to transform the decorator-based definition in a json schema.

If this is already possible, let me know what I am missing.

**Comment by vlapo** [comment] 2021-02-03 20:51
Duplicate of https://github.com/typestack/class-validator/issues/140. But I think we will drop schema based validation support soon.

**Closed by vlapo** 2021-02-03 20:51 UTC
Labels: flag: needs discussion, type: feature
