### ISSUE TITLE
fix: Missing properties do not cause a validation fail

### ISSUE THREAD

**Issue by richardweaver** [typestack/class-validator#1487] opened 2022-01-07 20:56 UTC
### Description
I have a simple DTO defined as a class with two non-optional string properties. When I try and validate (using a global ValidationPipe in Nestjs) an object that only includes one of the fields in the DTO, no validation error is thrown. I do not have the `skipMissingProperties` option set, and I can tell the validator is being called because if I do add an explicit `@IsDefined()` or any other validator like `@MinLength(1)` to the fields the validation correctly fails.

I've also tested by putting a manual call to validateOrReject in my controller method as below.

I'm using Nest 8.0 and class-validator 0.13.2.

**Minimal code-snippet showcasing the problem**
```
class CreateLocationDto {
  displayName: string;
  name: string;
}
validateOrReject({ n }).catch(errors => {
  console.log('Validation failed. Errors: ', errors);
});
console.log('Done');
```

### Expected behavior
An exception to be thrown and caught by the `catch` block, because I understood that the default behaviour of class-validator was to not validate missing properties unless `skipMissingProperties` is set.

### Actual behavior
No exception is thrown.

**Comment by jbjhjm** [comment] 2022-04-04 10:40
I cannot see any Decorators that tell class-validator what to do...?
You stated "DTO defined as a class with two non-optional string properties".
If you were assuming it would be enough to define `class {requiredProp:string}` as opposed to `class {optionalProp?:string}`, you are wrong. class-validator requires use of Decorators.

`skipMissingProperties` refers to props that are known and decorated, but `undefined` in the passed data.

**Comment by NoNameProvided** [comment] 2022-12-09 20:09
Closing as cannot reproduce, because no __minimal reproducible example__ was provided showcasing the problem. The example should:

- be as short as possible while clearly showcasing the problem
- has no external dependencies, only this lib
- the expected and actual behavior should be explained

**Closed as completed by NoNameProvided** 2022-12-09 20:09 UTC
Labels: type: fix, status: cannot reproduce
