### ISSUE TITLE
fix: schema-based validation not working

### ISSUE THREAD

**Issue by seriousManual** [typestack/class-validator#1155] opened 2021-06-30 11:37 UTC
We have been trying to use the schema based validation as described in the following sample:
https://github.com/typestack/class-validator/tree/develop/sample/sample5-schemas

We were not able to get the schema based validation to work and even executing the code from the provided sample did not work.

This looks like there has been a regression somewhere in the past?

**Comment by d-otter** [comment] 2021-11-03 17:21
The schema-based validation stopped working with version `0.12.0` - same issue, unfortunately I do not know the internal good enough to spot the root cause

**Comment by jbeckton** [comment] 2022-01-16 01:00
Looks like Schema Based validation will be deprecated in 1.0 https://github.com/typestack/class-validator/issues/178.

Bummer

**Comment by braaar** [comment] 2022-10-06 04:52
If you want schema based validation, check out the [zod readme's comparison with other validators](https://github.com/colinhacks/zod#comparison)

**Comment by pasear** [comment] 2022-10-06 05:01
I know alternatives, but this feature is in the document and should be a
bug.


2022年10月6日(木) 13:52 Brage Sekse Aarset ***@***.***>:

**Comment by braaar** [comment] 2022-10-06 05:10
It is currently a bug, but as this feature is going to be deprecated, it's not wise for this project to prioritise scarce maintainer time and effort towards fixing it. After almost a year of inactivity, we have gotten a little bit of maintainer involvement, and I think we will have to accept that we can't get everything we want, at least for the time being. See #1719 

PR is welcome, though. The first step to fixing this would be to write some tests for the schema based validation.

**Comment by pasear** [comment] 2022-10-06 05:23
How about removing it from the document?
It's still on the homepage (readme) and confusing peoole.
It's already broken and no need to keep it in the document.

2022年10月6日(木) 14:10 Brage Sekse Aarset ***@***.***>:

**Comment by braaar** [comment] 2022-10-06 05:44
> How about removing it from the document? It's still on the homepage (readme) and confusing peoole. It's already broken and no need to keep it in the document. 

That is a good compromise solution. I can make a PR.

**Comment by NoNameProvided** [comment] 2022-11-13 12:45
As mentioned in the thread, schema-based validation is deprecated and will be removed. The documentation has been updated, it now contains a suggestion of what libraries to use instead of class-validator.

To clarify, `class-validatior` will retain the ability to serialize validation meta-data and send it over the wire, but it will be considered an internal API and one must define their "validation schema" with decorators first.  

I am closing this issue as wontfix.

**Closed by NoNameProvided** 2022-11-13 12:45 UTC
Labels: type: fix, status: wontfix
