### ISSUE TITLE
question: How to use @Param('id') in DTO class

### ISSUE THREAD

**Issue by abdul15irsyad** [typestack/class-validator#1733] opened 2022-09-01 11:13 UTC
i want to make isUnique with custom validator, it already works but in update case it doesn't works because i need the id of the entity that i update to exclude it from checking the field, or there is another example to implement isUnique in NestJS with typeOrm? thanks

**Comment by braaar** [comment] 2022-09-02 09:42
Could you explain a little more clearly what you want to do, and perhaps write a little example?

Is it possible to implement what you need using `ValidateIf`?

```ts
import { customValidator } from './my-custom-validator.js';
import * as v from 'class-validator';

export class MyClass {
  
  @v.IsString()
  @v.IsOptional()
  id?: string;

  // the validators on this field will only be checked if id is not undefined 
  // that is, if ValidateIf's callback function returns true
  @v.ValidateIf((object: MyClass) => object.id !== undefined)
  @v.Validate(customValidator)
  myField: string
}
```

**Comment by NoNameProvided** [comment] 2022-11-13 14:42
Sorry, I cannot understand your problem. Closing this as cannot reproduce.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.

**Closed as completed by NoNameProvided** 2022-11-13 14:42 UTC
Labels: type: question
