### ISSUE TITLE
Possible to access fields outside current object using validateIf 

### ISSUE THREAD

**Issue by Dev-Drew** [typestack/class-validator#1490] opened 2022-01-13 04:15 UTC
I was trying to validate if a property based on the value a property that is stored in a different class. When an API request enters the service I'd like to check 
 
`Class Animal {
  type:string,
  attributes: Attributes
}`

`Class Attributes{
   @validateIf(Animal) => Animal.type === "Dog")
   canBark: boolean
}`
 

The problem is validate if only access to the current class. How do I validate based on the state another class?

**Comment by Nestor-SuperDev** [comment] 2022-08-10 05:23
I'm wondering the same question if it's possible, some hero?

**Comment by braaar** [comment] 2022-11-17 06:54
Duplicate of #1469. Let's move the discussion there.

**Closed as completed by braaar** 2022-11-17 06:54 UTC
Labels: type: question, status: duplicate
