### ISSUE TITLE
fix: IsPostalCode does not recognize Cayman Islands

### ISSUE THREAD

**Issue by mjrichards91** [typestack/class-validator#1791] opened 2022-11-17 20:31 UTC
### Description
Postal codes in the Cayman Islands return as invalid, i.e. KY1-1108. It doesn't seem like the locale KY is supported. 

**Minimal code-snippet showcasing the problem**
```ts
@IsPostalCode('any')
postalCode: string
```

### Expected behavior
Validation to be successful. 

### Actual behavior
Validation fails with the message "postalCode must be a postal code".

**Comment by NoNameProvided** [comment] 2022-11-18 11:04
Our postal code validation (as many other operators) is simply a call through to https://github.com/validatorjs/validator.js. After a quick look at the code and search on Google, it seems not all countries as supported and the `KY` code for the Cayman Islands is not present in the `PostalCodeLocale` type.

There is an open discussion about adding support for additional countries in validator.js here: https://github.com/validatorjs/validator.js/issues/722.

Closing this as invalid because the issue is in an upstream library.

**Closed as completed by NoNameProvided** 2022-11-18 11:04 UTC
Labels: type: fix, status: invalid / expired
