### ISSUE TITLE
fix: Unstable Unicode Regex

### ISSUE THREAD

**Issue by incetarik** [typestack/class-validator#1707] opened 2022-07-31 20:48 UTC
### Description
_I'm using NestJS, there I have validations which are done through this library._
I have decorated a class property with `@Matches` with a regex which has `ug` flags.
The problem is that this validator is returning `true` and `false` in order, repeatedly, and not stable.
Producing `true` and `false` (per following request) for the exact same string input.

To show you the exact place that I have caught, I'll share a picture to you so you can directly jump
to the line there and test by yourselves.

The Regex that is used:
```ts
/^\p{Alpha}{2,}[\p{Alpha}\s]{1,57}$/ug
```

The image ![Example Image](https://ibb.co/b5tnrgd)
The [link](https://ibb.co/b5tnrgd) if this is not visible to you.
The same image file is also attached here.

```ts
class InputDto {
  @IsString()
  @IsOptional()
  @Length(3, 60)
  @Matches(/^\p{Alpha}{2,}[\p{Alpha}\s]{1,57}$/ug, {
    message: 'The input is not valid'
  })
  readonly fullName?: string
}
```

### Expected behavior
Returning `true` for all execution/validation.

### Actual behavior
Returning `true` and `false` and `true` and so on for each validation.

![Example](https://user-images.githubusercontent.com/14037316/182044778-2af9eff1-b01e-42dd-8f13-521a25b2fb05.png)

**Comment by braaar** [comment] 2022-08-16 06:48
Could you try to set up a minimal reproduction of this behaviour in [runkit](https://npm.runkit.com/) or something similar?

**Comment by incetarik** [comment] 2022-08-19 22:13
> Could you try to set up a minimal reproduction of this behaviour in [runkit](https://npm.runkit.com/) or something similar?

[Here it is](https://runkit.com/incetarik/class-validator) @braaar, please check this out and play with it as you wish.

**Comment by braaar** [comment] 2022-08-23 10:43
Damn, this is really something. I'm not very knowledgeable about regex, so I don't have the faintest idea why this is happening.

**Comment by braaar** [comment] 2022-08-23 10:45
~~I tried to put your regex in [Regex101](https://regex101.com/) and it says it's an invalid expression. What's up with that?~~

Nevermind, I'm dumb.

**Comment by incetarik** [comment] 2022-09-23 10:51
Any news about this @braaar ?

**Comment by braaar** [comment] 2022-09-23 11:34
This is an upstream issue in validator.js, it seems

**Comment by braaar** [comment] 2022-11-15 10:55
I don't see how we would fix this in this project. We are just calling an upstream validation function. 

This should be fixed in validator.js. See [validator.js#1768](https://github.com/validatorjs/validator.js/issues/1768).

For now you can implement your own custom regex validator that uses the fix described in [the comments to that issue](https://github.com/validatorjs/validator.js/issues/1768#issuecomment-1135574230).

**Closed as completed by braaar** 2022-11-15 10:55 UTC
Labels: type: fix

**Comment by NoNameProvided** [comment] 2022-11-15 11:11
@braaar don't forget to remove the needs triage label when we discovered what is the root cause of the report.
