### ISSUE TITLE
fix: validate() return errors when everything is fine

### ISSUE THREAD

**Issue by abasso-ote** [typestack/class-validator#1223] opened 2021-08-02 15:00 UTC
### Description

I'm using class-validator to check if the body of my request is a valid object.
I use IsDefined() and Matches(<my regex>)  decorator
**Minimal code-snippet showcasing the problem**
 

```ts
// classfile
const mailRegex = new RegExp(/[a-zA-Z0-9\.\-\_]{2,}@mydomain\.com/gm)
class MailerInfo {
    @IsDefined()
    @Matches(mailRegex)
    @Expose()
    public loginMail: string;
    @IsDefined()
    @Expose()
    public encryptedPass: string;
    @Matches(mailRegex)
    @Expose()
    public emitterMail: string;
}
//controller
export function setMailerInfo(req, res) {
    new Promise((resolve, reject) => {
        const mailerInfo = plainToClass(MailerInfo,req.body)
        validate(mailerInfo,{skipMissingProperties:true}).then(errors=>{
            if(errors.length > 0){
                console.log(errors);
                reject("body request is malformed")
            }else{
                console.log("everything is fine")
                console.log(mailerInfo)
                req.app.set('mailerInfo', mailerInfo);
                resolve(true);
            }
        })
    }).then(() => {
        res.status(200).send();
    }).catch(err => {
        console.error(err)
        res.status(400).json({"message": "An error occurred during your request"})
    })
}
```

### Expected behavior

The validate function return errors only when they really exist 
### Actual behavior

the validate function alternante between finding errors and not finding errors with the same input 

example of console output : 
```
everything is fine
MailerInfo {
  loginMail: 'username@mydomain.com',
  encryptedPass: 'myecryptedpass',
  emitterMail: undefined
}
[
  ValidationError {
    target: MailerInfo {
      loginMail: 'username@mydomain.com',
      encryptedPass: 'myecryptedpass',
      emitterMail: undefined
    },
    value: 'username@mydomain.com',
    property: 'loginMail',
    children: [],
    constraints: {
      matches: 'loginMail must match /[a-zA-Z0-9\\.\\-\\_]{2,}@mydomain\\.com/gm regular expression'
    }
  }
]
body request is malformed
everything is fine
MailerInfo {
  loginMail: 'username@mydomain.com',
  encryptedPass: 'myecryptedpass',
  emitterMail: undefined
}
[
  ValidationError {
    target: MailerInfo {
      loginMail: 'username@mydomain.com',
      encryptedPass: 'myecryptedpass',
      emitterMail: undefined
    },
    value: 'username@mydomain.com',
    property: 'loginMail',
    children: [],
    constraints: {
      matches: 'loginMail must match /[a-zA-Z0-9\\.\\-\\_]{2,}@mydomain\\.com/gm regular expression'
    }
  }
]
body request is malformed
everything is fine
MailerInfo {
  loginMail: 'username@mydomain.com',
  encryptedPass: 'myecryptedpass',
  emitterMail: undefined
}
[
  ValidationError {
    target: MailerInfo {
      loginMail: 'username@mydomain.com',
      encryptedPass: 'myecryptedpass',
      emitterMail: undefined
    },
    value: 'username@mydomain.com',
    property: 'loginMail',
    children: [],
    constraints: {
      matches: 'loginMail must match /[a-zA-Z0-9\\.\\-\\_]{2,}@mydomain\\.com/gm regular expression'
    }
  }
]
body request is malformed
everything is fine
MailerInfo {
  loginMail: 'username@mydomain.com',
  encryptedPass: 'myecryptedpass',
  emitterMail: undefined
}
[
  ValidationError {
    target: MailerInfo {
      loginMail: 'username@mydomain.com',
      encryptedPass: 'myecryptedpass',
      emitterMail: undefined
    },
    value: 'username@mydomain.com',
    property: 'loginMail',
    children: [],
    constraints: {
      matches: 'loginMail must match /[a-zA-Z0-9\\.\\-\\_]{2,}@mydomain\\.com/gm regular expression'
    }
  }
]
body request is malformed
everything is fine
MailerInfo {
  loginMail: 'username@mydomain.com',
  encryptedPass: 'myecryptedpass',
  emitterMail: undefined
}
[
  ValidationError {
    target: MailerInfo {
      loginMail: 'username@mydomain.com',
      encryptedPass: 'myecryptedpass',
      emitterMail: undefined
    },
    value: 'username@mydomain.com',
    property: 'loginMail',
    children: [],
    constraints: {
      matches: 'loginMail must match /[a-zA-Z0-9\\.\\-\\_]{2,}@mydomain\\.com/gm regular expression'
    }
  }
]
body request is malformed
everything is fine
MailerInfo {
  loginMail: 'username@mydomain.com',
  encryptedPass: 'myecryptedpass',
  emitterMail: undefined
}
[
  ValidationError {
    target: MailerInfo {
      loginMail: 'username@mydomain.com',
      encryptedPass: 'myecryptedpass',
      emitterMail: undefined
    },
    value: 'username@mydomain.com',
    property: 'loginMail',
    children: [],
    constraints: {
      matches: 'loginMail must match /[a-zA-Z0-9\\.\\-\\_]{2,}@mydomain\\.com/gm regular expression'
    }
  }
]
body request is malformed
everything is fine
MailerInfo {
  loginMail: 'username@mydomain.com',
  encryptedPass: 'myecryptedpass',
  emitterMail: undefined
}
[
  ValidationError {
    target: MailerInfo {
      loginMail: 'username@mydomain.com',
      encryptedPass: 'myecryptedpass',
      emitterMail: undefined
    },
    value: 'username@mydomain.com',
    property: 'loginMail',
    children: [],
    constraints: {
      matches: 'loginMail must match /[a-zA-Z0-9\\.\\-\\_]{2,}@mydomain\\.com/gm regular expression'
    }
  }
]
body request is malformed
```

**Comment by hungtcs** [comment] 2021-08-31 08:00
+1, I can't use `@Expose({ group: ['some'] })` with `@IsString()` together.

**Comment by greenreign** [comment] 2023-02-03 15:47
I'm having the same problem with `@Matches(/[^+|\-"*()~]+$/g)`
```
{ result: true, pattern: /[^+|\-"*()~]+$/g, str: 's' }
{ result: false,pattern: /[^+|\-"*()~]+$/g, str: 's' }
```

**Comment by greenreign** [comment] 2023-02-03 17:24
For me if I update the regexp to a string the behavior is corrected
`@Matches('[^+|\\-"*()~]+$')`

**Comment by braaar** [comment] 2023-02-08 06:47
I believe this is a duplicate of #1707. This behaviour is not caused by class-validator, and should be fixed upstream. [See issue in upstream repository](https://github.com/validatorjs/validator.js/issues/1768).

**Closed by braaar** 2023-02-08 06:47 UTC
Labels: type: fix, status: needs triage
