### ISSUE TITLE
cannot validate express post body. Error, an unknown value was passed to the validate function 

### ISSUE THREAD

**Issue by EdijaeCrusar** [typestack/class-validator#1663] opened 2022-05-30 21:36 UTC
### Description

When i convert express post body to a class instance using class-transformer, and then try to validate it, i get the error `{"unknownValue":"an unknown value was passed to the validate function"}`

**Minimal code-snippet showcasing the problem**

```
import express from 'express';
import { validate } from 'class-validator';
import Product from '../models/Product.js';
import Response from '../models/Response.js';
import {plainToClass, plainToInstance} from 'class-transformer';

export async function validateProduct(req:express.Request, res: express.Response, next){
    
    if(req.method != "GET" && req.method != "DELETE"){
        console.log('product route. validating %s', req.method)
        let product = plainToInstance(Product, req.body);
 
      let errors = await validate(pd as Product,{skipMissingProperties: true,whitelist:true, forbidUnknownValues:true})
      console.log('product validation errors are   %s', JSON.stringify(errors));
      if(errors.length > 0){
          let response = new Response()
          response.success = false;
          response.errors = errors.map((error) => JSON.stringify(error.constraints));
          res.status(400).json(response)
      }else{
        next()
      }  
    }else{
        next()
      }
}
```
 

```ts

```

### Expected behavior
validate the item

### Actual behavior
not validating the item but returns the error above.

**Comment by Thomas-1985** [comment] 2022-06-20 20:55
Hi

I had the same issue, maybe that helps:
https://github.com/typestack/class-validator/issues/1474

**Comment by NoNameProvided** [comment] 2022-12-09 19:31
Closing as cannot reproduce, because no [minimum reproducible example](https://minimum-reproduction.wtf/) was provided.

Please provide a __minimal__ reproducible example showcasing your problem. The example should:

- be as short as possible while clearly showcasing the problem
- has no external dependencies, only this lib
- the expected and actual behavior should be explained

**Closed as completed by NoNameProvided** 2022-12-09 19:31 UTC
Labels: type: fix, status: cannot reproduce
