### ISSUE TITLE
fix: IsUrl() fails on urls with "%20" or spaces

### ISSUE THREAD

**Issue by kliuiev-io** [typestack/class-validator#1417] opened 2021-11-22 11:35 UTC
### Description

The urls like `https://google.com/search?q=test%20url` and `https://google.com/search?q=test url` fail on @IsUrl() validation, `https://google.com/search?q=testurl` works well

**Minimal code-snippet showcasing the problem**
 

```ts
// Nest.js
export default class TestDto {
  @IsUrl()
  url: string;
}
```

### Expected behavior

`https://google.com/search?q=test%20url` and `https://google.com/search?q=test url` are correct URLs.

### Actual behavior

`https://google.com/search?q=test%20url` and `https://google.com/search?q=test url` are recognized as incorrect URLs

**Comment by kliuiev-io** [comment] 2021-11-22 11:39
![image](https://user-images.githubusercontent.com/72439852/142855352-de981e18-2c49-499c-ae42-25f60b814dbb.png)
![image](https://user-images.githubusercontent.com/72439852/142855388-bab95e9d-25be-4c59-8c28-71c511c4607c.png)

**Comment by Kignuf** [comment] 2021-12-02 10:45
Hello,

I am willing to help solve this issue, however I've tried adding a unit test to reproduce the problem but it didn't:
```
expect(isURL('https://google.com/search?q=test%20url')).toBeTruthy();
```

Maybe I missed something ?

Thanks

**Comment by samvanf** [comment] 2021-12-03 15:33
Hello, I've also tried this out, and
`https://google.com/search?q=test%20url` is being treated as a correct URL. However, `https://google.com/search?q=test url` is not, and I don't think that should be recognized as a correct URL.

**Comment by NoNameProvided** [comment] 2022-12-16 00:01
This is working well for me:

```ts
import { IsUrl, validate } from 'class-validator';

class MyPayload {
  @IsUrl()
  value?: string;

  constructor(value?: string) {
    this.value = value;
  }
}

// Will pass as expected
validate(new MyPayload('https://google.com/search?q=test%20url')).then(console.log);
validate(new MyPayload('https://google.com/search?q=testurl')).then(console.log);

// Will fail as expected
validate(new MyPayload('https://google.com/search?q=test url')).then(console.log);

```

Closing as cannot reproduce.

**Closed as completed** 2022-12-16 00:01 UTC
Labels: type: fix, status: cannot reproduce
