### ISSUE TITLE
how to validate array of objects

### ISSUE THREAD

**Issue by adnan-kamili** [typestack/class-validator#108] opened 2017-07-23 05:53 UTC
I tried following but it didn't work:

```javascript
    @IsArray()
    @ValidateNested()
    customFields: CustomFieldViewModel[];
```

**Comment by Poitrin** [comment] 2017-08-03 10:09
What’s the error message?
Are the items in the customFields array all instances of the CustomFieldViewModel class?

**Comment by NoNameProvided** [comment] 2017-08-06 16:02
There is an open issue for this (#83). `@ValidateNested()` doesn't work with custom objects. 

If you have the same issue, please close this as it is the duplicate of #83

**Comment by NoNameProvided** [comment] 2018-01-08 08:11
Closing this in favor of #83.

**Closed by NoNameProvided** 2018-01-08 08:11 UTC
