### ISSUE TITLE
feature: Language support

### ISSUE THREAD

**Issue by aurelien-robineau** [typestack/class-validator#789] opened 2020-10-21 15:49 UTC
### Description
`class-validator` is usefull but errors are only in english (or have I missed something ?) It is quite inconvenient to manually enter messages when it could be automatic.

### Proposed solution
This could be done in the `ValidatorOptions` interface via a `locale` property.
``` javascript
export interface ValidatorOptions {
    locale: 'fr',
}
```
Or in the decorators options.
``` javascript
@Max(10, { locale: 'fr' })
```

**Comment by Kiliandeca** [comment] 2020-10-31 14:42
Hi, it's a duplicate of #169

**Closed by Kiliandeca** 2020-10-31 14:42 UTC
Labels: status: duplicate
