### ISSUE TITLE
[Bug] $value is not parsed in message

### ISSUE THREAD

**Issue by willin** [typestack/class-validator#1046] opened 2021-04-30 06:57 UTC
### Description

v0.13.1

**Minimal code-snippet showcasing the problem**
 

```ts
import { MinLength, Matches, validateSync } from 'class-validator';

class Demo {
  @MinLength(10, {
    // here, $constraint1 will be replaced with "10", and $value with actual supplied value
    message: 'Title is too short. Minimal length is $constraint1 characters, but actual is $value'
  })
  @Matches(/^$/, {
    message: '$target, $property, $value, $constraint1'
  })
  name: string;

  constructor(obj: any) {
    Object.assign(this, obj);
  }
}

const demo = new Demo({
  name: true
});

console.log(
  validateSync(demo, {
    // dismissDefaultMessages: true
  })
);
console.log(Object.values(validateSync(demo)[0].constraints));

```

### Expected behavior

`$value` should be  parsed.

### Actual behavior

```
[
  ValidationError {
    target: Demo { name: true },
    value: true,
    property: 'name',
    children: [],
    constraints: {
      matches: 'Demo, name, $value, /^$/',
      minLength: 'Title is too short. Minimal length is 10 characters, but actual is $value'
    }
  }
]
[
  'Demo, name, $value, /^$/',
  'Title is too short. Minimal length is 10 characters, but actual is $value'
]
```

**Comment by c0d3ster** [comment] 2021-09-23 20:12
Also experiencing this issue on a nested object validation if anyone has found a solution?

**Comment by pmirand6** [comment] 2022-06-27 03:46
I was going crazy with this, until I discovered that the message can be used as a function.
All you have to do is to use the `message` as function, and then access to the value passed: 

![image](https://user-images.githubusercontent.com/26637050/175855887-3d02c76d-35d7-4260-86ed-c8325584758e.png)

[Here](https://github.com/typestack/class-validator#passing-context-to-decorators:~:text=Also%20you%20can%20provide%20a%20function%2C%20that%20returns%20a%20message.%20This%20allows%20you%20to%20create%20more%20granular%20messages%3A) you can see an example.

Hope it's Help. 

At the moment, I'm still trying to remove the prefix from error message [can't ](https://github.com/typestack/class-validator/issues/1426)

**Comment by NoNameProvided** [comment] 2022-12-09 20:46
Duplicate of https://github.com/typestack/class-validator/issues/921.

**Closed by NoNameProvided** 2022-12-09 20:46 UTC
Labels: type: fix, status: duplicate
