### ISSUE TITLE
validator args.value.length NOT reflecting correct length of value

### ISSUE THREAD

**Issue by st-clair-clarke** [typestack/class-validator#106] opened 2017-07-19 10:17 UTC
Hi,
I have the following:

```
export class Onset {
  @IsNotEmpty( { message: 'Input required' } )
  @MinLength( 6, { message: minLength6Fn } )
  mode: string
}

export function minLength6Fn( args: ValidationArguments ) {
  switch ( args.value.length ) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return `Too short, minimum length is ${args.constraints[ 0 ]} characters, but actual is ${args.value.length}`
  }
}
```

Validation is done as shown below:

```
 onset = new Onset()
onset.model = 'Sudden'

          transformAndValidate( Onset, currentValue )
                  .then( ( onset: Onset ) => {
        
                  } )
                  .catch( errors => {
                    console.log( `onset errors | ${JSON.stringify( errors ) }` )
                    console.log( errors )
        
                    let propError = findPropertyValidationErrors( errors, 'mode' )
                    console.log( propError )
                  } )
```

The validation error printed to console is '["Too short, minimum length is 6 characters, but actual is 5"]

The ${args.value.length} in return `Too short, minimum length is ${args.constraints[ 0 ]} characters, but actual is ${args.value.length}` is NOT reflecting the true length of the input.

Is this a bug?

**Comment by NoNameProvided** [comment] 2018-01-08 07:46
Hi @st-clair-clarke! 

As I can see you are using a different library. `class-validator` doesn't expose a `transformAndValidate` function.

I cannot reproduce your issue with this library. I tried with this code:

```ts
import { MinLength, IsNotEmpty, ValidationArguments, validate } from 'class-validator';

export function minLength6Fn(args: ValidationArguments) {
  return `Too short, minimum length is ${args.constraints[0]} characters,` + 
    `but actual is ${args.value.length}`;
}

export class Onset {
  @IsNotEmpty({ message: 'Input required' })
  @MinLength(6, { message: minLength6Fn })
  model: string
}

const instance = new Onset()
instance.model = 'Sudden'

validate(instance).then(console.log);
```

This passes with zero errors. Trying with a shorter text like `Sudde` will trigger the `MinLength` error with the correct length value: 

```
'Too short, minimum length is 6 characters, but actual is 5' 
```

I will go ahead and close this, feel free to continue the conversations if you have any question.

**Closed by NoNameProvided** 2018-01-08 07:46 UTC
