### ISSUE TITLE
Validation for Locale probably with a decorator IsLocale() ?

### ISSUE THREAD

**Issue by rubiin** [typestack/class-validator#408] opened 2019-08-21 04:05 UTC
This validation that comes with IsLocale() decorator will be used to determine if a value is a valid locale or not . If accepted I can do it and send a PR

**Comment by vlapo** [comment] 2019-08-23 07:21
Feel free add any functionality. But please be sure what do you mean under term of "locale". It could be language code or geographic/country code. And of course I am pretty sure there is not only one standard like "ISO 639", "ISO_3166", RFC 4646, ...

**Comment by l2ubin** [comment] 2019-08-23 09:54
IETF locale tags like en-US or en-GB

**Comment by l2ubin** [comment] 2019-08-23 09:55
we can include the other standards for future enhancement

**Comment by rubiin** [comment] 2019-09-04 08:50
@vlapo

**Comment by daweedm** [comment] 2019-09-16 17:01
@rubiin 
This library could be useful for your PR : https://www.npmjs.com/package/locale-code 

```js
console.log(LocaleCode.validate('en-US')); // true

console.log(LocaleCode.validate('en_US')); // false

console.log(LocaleCode.validate('bb-XX')); // false
```

NB: hyphen-separated locales are standard (fr-BE) while the ones with underscore are not (fr_BE), see http://tools.ietf.org/html/rfc5646

**Comment by rubiin** [comment] 2019-09-25 17:31
@vlapo I can do a pr. Also can we add hacktoberfest labels on PRs

**Comment by rubiin** [comment] 2019-09-26 09:48
I will be using more like a set of already available locales instead of a lib

**Comment by rubiin** [comment] 2019-09-27 07:22
I will be using more like a set of already available locales instead of a lib. I found a list at a lib https://github.com/expandjs/expandjs/blob/master/lib/languages.js
@vlapo

**Comment by rubiin** [comment] 2019-09-29 11:40
I will be using more like a set of already available locales instead of a lib. I found a list at a lib https://github.com/expandjs/expandjs/blob/master/lib/languages.js
@vlapo  @NoNameProvided  . Also can we put hactoberfest label to the issue

**Comment by vlapo** [comment] 2019-10-01 17:59
Be careful. New lib could increase `class-validator` package size (we have already problem with this).

**Comment by rubiin** [comment] 2019-10-01 18:00
@vlapo I am just going to use the list of locales in the lib not the actual lib so nothing to worry

**Comment by vlapo** [comment] 2019-10-16 11:30
Duplicate of #425

**Closed by vlapo** 2019-10-16 11:30 UTC
Labels: flag: accepting PRs, hacktoberfest, type: feature
