### ISSUE TITLE
check if two fields values are equal

### ISSUE THREAD

**Issue by rubiin** [typestack/class-validator#493] opened 2019-12-20 07:42 UTC
I am implementing password change feature and would like to know how do we confirm if the fields password and confirm_password are the same? @vlapo

**Comment by rubiin** [comment] 2019-12-20 07:56
@vlapo  as this seems to be a common usecase how about a validator for this, I can submit a pr

**Comment by vlapo** [comment] 2020-01-10 12:53
Duplicate of https://github.com/typestack/class-validator/issues/486

**Closed by vlapo** 2020-01-10 12:53 UTC
