### ISSUE TITLE
type `isIn` is not working in validation schema

### ISSUE THREAD

**Issue by jiturawat94** [typestack/class-validator#575] opened 2020-04-06 12:03 UTC
`properties: {
        paymentReceiptStatus: [{
            type: "isIn",
            constraints: [["YES", "NO"]]
        }],
        paymentReceiptStatusMarker: [{
            type: "isNumber"
        }]
    }`

isIn validation is not working

**Comment by vlapo** [comment] 2020-04-07 20:24
Looks like we have a bug in schema validation. Change `paymentReceiptStatusMarker: [{ type: "isNumber" }]` to `paymentReceiptStatusMarker: [{ type: "isNumber", constraints: [] }]` for fast fix. 

Related to https://github.com/typestack/class-validator/issues/516

**Comment by vlapo** [comment] 2020-04-07 20:24
Duplicate of https://github.com/typestack/class-validator/issues/516

**Comment by jiturawat94** [comment] 2020-04-08 11:49
i was talking about this isIn not working
properties: { paymentReceiptStatus: [{ type: "isIn", constraints: [["YES", "NO"]] }]

**Comment by vlapo** [comment] 2020-04-08 12:44
I know and I tested it without `paymentReceiptStatusMarker` and it works. https://stackblitz.com/edit/class-validator-gh575?file=index.ts

**Comment by NoNameProvided** [comment] 2020-08-08 23:57
Schema-based validation will be deprecated in the future probably as a result marking this as low prio.

**Comment by NoNameProvided** [comment] 2022-11-13 13:34
Schema-based validation is deprecated, it has been removed from the docs in https://github.com/typestack/class-validator/commit/7cd7546fe965ea668b49feccf435badc130d9490. If you need to use schema-based validation I recommend using one of the other available libraries.

**Closed by NoNameProvided** 2022-11-13 13:34 UTC
Labels: type: fix, status: wontfix
