### ISSUE TITLE
Schema example in README.md not work

### ISSUE THREAD

**Issue by LILU-WEB** [typestack/class-validator#595] opened 2020-04-29 13:53 UTC
I just copy and paste, change object value and try to trigger errors...but result shows empty array...
please help, give me some clues... i was trapped by this in hours...thank you

----------- terminal info ---------------
[]
Validation succeed.
------------------------------------------
```javascript
import {ValidationSchema, registerSchema, validate} from "class-validator";
export let UserValidationSchema: ValidationSchema = { // using interface here is not required, its just for type-safety
    name: "myUserSchema", // this is required, and must be unique
    properties: {
        firstName: [{
            type: "minLength", // validation type. All validation types are listed in ValidationTypes class.
            constraints: [2]
        }, {
            type: "maxLength",
            constraints: [20]
        }],
        lastName: [{
            type: "minLength",
            constraints: [2]
        }, {
            type: "maxLength",
            constraints: [20]
        }],
        email: [{
            type: "isEmail"
        }]
    }
};

registerSchema(UserValidationSchema);
const user = { firstName: "1", secondName: "1", email: "johnycage.com" };
validate("myUserSchema", user).then(errors => {
    console.log(errors)
    if (errors.length > 0) {
        console.log("Validation failed: ", errors);
    } else {
        console.log("Validation succeed.");
    }
});
```

**Comment by LILU-WEB** [comment] 2020-04-29 14:19
UPDATE:  "class-validator": "^0.11.1" works but email value had to add constraints: []...
lookes there are something wrong in new release...
back to 0.11.1 now...can anyone here help to fix the bug and build a new release?

**Comment by devillexio** [comment] 2020-04-29 16:03
> I just copy and paste, change object value and try to trigger errors...but result shows empty array...

I'm seeing exactly the same. "v0.11.1" returns array of validation errors, where "v0.12.2" returns empty array.

I've looked through the changelogs for any breaking changes, but couldn't find anything related.

**Comment by vlapo** [comment] 2020-05-04 20:02
It is related to last big refactor. We do not have tests for schema features so I do not realised we broke this feature completely.
Sorry for that. I will try fix this in short time.

**Comment by snaerth** [comment] 2020-05-29 15:53
@vlapo is any update on the issue

**Comment by aabuelenin** [comment] 2020-07-29 22:28
so I wasted half a day debugging class-validator trying to figure out what AM I doing wrong. You might ask, why didn't I search the open issues instead of wasting that much time? ok, well, who would have thought that any library could fail the most basic scenario? a validation library that can't perform any validation is unheard of.

So, as everyone here, I'm wondering is there's any update on this issue and is this project is still alive?

I understand that open source developers have other responsibilities, but please set the expectations of anyone using your code right.

**Comment by NoNameProvided** [comment] 2020-08-03 07:08
FYI, soon we I will open a discussion about removing the schema validation functionality at all from class-validator. There are libraries dedicated for that, so we should not roll our own but focus on the decorator based validation.

**Comment by akshayr-tavisca** [comment] 2020-11-06 07:51
@NoNameProvided  Can you suggest a package which does schema validations (Typescript)

**Comment by Varkal** [comment] 2020-11-06 09:44
@akshayr-tavisca I use [Joi](https://joi.dev/) in my current project

**Comment by snaerth** [comment] 2020-12-14 15:19
@NoNameProvided Is there any update on this issue whether your are going to include it in the future or not. 
Also not to mention that current version is broken

**Comment by whmori17** [comment] 2021-05-31 09:39
Hi guys! How's the issue going? There's something we can do to help?

**Comment by Gbuomprisco** [comment] 2021-08-28 23:51
Why not at least update the README and say "Don't even try"? Also spent a whole day debugging this :|

**Comment by J-Zet** [comment] 2022-10-05 14:48
Hi guys! Any update on this, about 2.5 years later?

**Comment by braaar** [comment] 2022-10-06 04:47
Thanks for bumping this (I had no idea this features was broken), but this issue will probably not see a lot of action in the near future, as we have quite low maintainer activity and no way to add more maintainers. See #1719

**Comment by braaar** [comment] 2022-10-06 04:48
I agree with @NoNameProvided here. This feature seems like a tacked on afterthought to me. 

For schema based validation, I would recommend [zod](https://github.com/colinhacks/zod).

Duplicate of this issue: https://github.com/typestack/class-validator/issues/1155

**Comment by NoNameProvided** [comment] 2022-11-13 12:46
As mentioned in the thread, schema-based validation is deprecated and will be removed. The documentation has been updated, it now contains a suggestion of what libraries to use instead of class-validator.

To clarify, `class-validatior` will retain the ability to serialize validation meta-data and send it over the wire, but it will be considered an internal API and one must define their "validation schema" with decorators first.  

I am closing this issue as wontfix.

**Closed by NoNameProvided** 2022-11-13 12:46 UTC
Labels: type: fix, status: wontfix
