### ISSUE TITLE
Feature Request, Generating JSON Schema from TypeScript Class

### ISSUE THREAD

**Issue by xe4me** [typestack/class-validator#129] opened 2017-10-09 03:43 UTC
Hi 
I'm submitting a feature request which will give me the functionality to convert the Decorator validators that I have implemented in my typescript classes, to a JSON schema.

There is a lot of cases, where we don't have TypeScript ( like IOS) but there is a JSON schema validator available that would validate the payload against the JSON Schema.
We don't want to write the whole validation rules, which we've written with your beautiful decorators in Typescript, again in JSON schema.

This will be helpful for cases where the definition of the validation will be used by different platforms, like Angular and others and for whatever reason, class-validator is not available, but the generated JSON schema could be reused by others.

I'd be more than glad to implement this feature and create a pull request myself if you guys point me to a starting point direction and I'll start right away.

**Comment by abenhamdine** [comment] 2017-12-06 09:14
What about using https://github.com/typestack/class-transformer#classtoplain then JSON.stringify the object ?

**Comment by braaar** [comment] 2022-11-16 20:07
Closing as duplicate of #5.

**Closed by braaar** 2022-11-16 20:07 UTC
Labels: type: feature, priority: low, flag: schema-based-validation
