### ISSUE TITLE
Is there any way to do sequential validation?

### ISSUE THREAD

**Issue by kapv89** [typestack/class-validator#227] opened 2018-06-28 15:44 UTC
I am using this library on the server side with [nestjs](https://nestjs.com/). How do I handle the scenario where I want certain validations to run only if the validations preceding it pass? For example, consider this scenario:

```ts
class CreateTagDto {
  @IsString()
  @MinLength(3)
  @UniqueTagName({ message: '...' }) // custom validation decorator
  name: string;
}
```
The `@UniqueTagName` decorator hits the db, so it has an IO cost. This cost can be minimised if this decorator is run only when the decorators preceding it pass. Is there some way to do this?

**Comment by NoNameProvided** [comment] 2018-07-18 21:42
There is currently no way of doing this.

**Comment by NoNameProvided** [comment] 2018-07-18 21:42
This is duplicate of #134.

**Comment by kenberkeley** [comment] 2020-02-03 10:42
Very useful feature, wish to have.

**Comment by vlapo** [comment] 2020-04-19 18:49
Duplicate of #134

**Closed by vlapo** 2020-04-19 18:49 UTC
Labels: status: duplicate, type: feature
