### ISSUE TITLE
fix: Cannot find module 'class-validator/types/metadata/ValidationMetadata'

### ISSUE THREAD

**Issue by arsenij-melihov** [typestack/class-validator#1624] opened 2022-04-19 09:59 UTC
### Description
When I am trying to import the `ValidationMetadata` class in order to implement my own custom validator I get the runtime error: `"Cannot find module 'class-validator/types/metadata/ValidationMetadata'"`. 

This issue is similar to: https://github.com/typestack/class-validator/issues/798.

Versions:
`"typescript": "^4.0.3"`
`"class-validator": "^0.13.2"`

**Minimal code-snippet showcasing the problem**
The reproduction repository: https://github.com/arsenij-melihov/class-validator-ValidationMetadata-import
```ts
import { ValidationMetadata } from 'class-validator/types/metadata/ValidationMetadata';
import { ValidationMetadataArgs } from 'class-validator/types/metadata/ValidationMetadataArgs';

function main(): void {
  const args = ({} as unknown) as ValidationMetadataArgs;
  const metadata = new ValidationMetadata(args);

  console.log({
    args,
    metadata,
  });
}

main();
```
Run: 
```sh
npx ts-node index.ts
```

### Expected behavior
No errors

### Actual behavior
Error: `Cannot find module 'class-validator/types/metadata/ValidationMetadata'`

**Comment by epoiate** [comment] 2022-05-06 18:19
Facing the same issue.

**Comment by epoiate** [comment] 2022-05-06 18:24
Actually, #686 seems to work for me.

**Comment by kasir-barati** [comment] 2022-05-09 13:41
@epoiate @arsenij-melihov @NoNameProvided @pleerock any thought on allowing users to create custom decorators with the same logic as `ValidateIf` has. I need more freedom. I need to do this in class-validator:
```ts
class A {
    anotherThing: string;
    
    @ThrowErrorIf(
        (a: A) =>
            a.anotherThing === 'Some_predefined_string' &&
            !isNil(a.anything),
        {
            message: 'You cannot pass anything while you set anotherThing to Some_predefined_string'
        },
    )
    anything: string;
}
```

**Comment by hastom** [comment] 2022-07-18 08:45
@arsenij-melihov as a workaround you can create a `.d.ts` file with
```ts
declare module 'class-validator/cjs/metadata/ValidationMetadata' {
  import { ValidationMetadata as __ValidationMetadata } from 'class-validator/types/metadata/ValidationMetadata'
  export const ValidationMetadata = __ValidationMetadata
}
```
And then 
```ts
import { ValidationMetadata } from 'class-validator/cjs/metadata/ValidationMetadata'
```
wherever you need it.

But this is really ugly and I argree, that conditional optional decorators are needed

**Comment by TerryJoo** [comment] 2022-10-07 04:57
## My solution
### Before
```typescript
import { ValidationMetadata } from 'class-validator/types/metadata/ValidationMetadata';
import { ValidationMetadataArgs } from 'class-validator/types/metadata/ValidationMetadataArgs';
```
### After
```typescript
import { ValidationMetadata, ValidationMetadataArgs } from 'class-validator';
```

**Comment by NoNameProvided** [comment] 2022-12-09 20:24
Closing this as cannot reproduce. Both should be importable.

**Closed as completed by NoNameProvided** 2022-12-09 20:24 UTC
Labels: type: fix, status: cannot reproduce
