### ISSUE TITLE
fix: schema-based validation does not work

### ISSUE THREAD

**Issue by thorek** [typestack/class-validator#611] opened 2020-05-14 09:57 UTC
Tested with the example from the README - the following validation will always show "Validation succeed". 
Even in case the object should not pass. 

``` 
 let UserValidationSchema: ValidationSchema = { // using interface here is not required, its just for type-safety
    name: "myUserSchema", // this is required, and must be unique
    properties: {
        firstName: [{
            type: "minLength", // validation type. All validation types are listed in ValidationTypes class.
            constraints: [2]
        }, {
            type: "maxLength",
            constraints: [20]
        }],
        lastName: [{
            type: "minLength",
            constraints: [2]
        }, {
            type: "maxLength",
            constraints: [20]
        }],
        email: [{
            type: "isEmail"
        }]
    }
  };
  registerSchema(UserValidationSchema); // if schema is in .json file, then you can simply do registerSchema(require("path-to-schema.json"));
  const user = { firstName: "J", secondName: "Cage", email: "johny", some: "thing" };
  validate("myUserSchema", user).then(errors => {
      if (errors.length > 0) {
          console.log("Validation failed: ", errors);
      } else {
          console.log("Validation succeed.");
      }
  });
```

**Comment by ozzywalsh** [comment] 2020-05-17 19:51
Duplicate of #595.

**Comment by NoNameProvided** [comment] 2020-08-09 00:02
Schema-based validation will be deprecated in the future probably as a result marking this as low prio.

**Closed** 2020-08-09 00:02 UTC
Labels: priority: low, status: duplicate, type: fix
