### ISSUE TITLE
vscode shows an error that IsNotEmpty is not exported from class-validator but the app works just fine

### ISSUE THREAD

**Issue by a4amado** [typestack/class-validator#1517] opened 2022-01-27 21:27 UTC
Here is the details <a href="https://github.com/microsoft/vscode/issues/141672">https://github.com/microsoft/vscode/issues/141672</a>

**Comment by NoNameProvided** [comment] 2022-11-20 19:02
Probably duplicate of https://github.com/typestack/class-validator/issues/1412.

**Closed as completed** 2022-11-20 19:01 UTC
Labels: type: fix, status: invalid / expired
