### ISSUE TITLE
fix: ValidateNested changes the validated data

### ISSUE THREAD

**Issue by heynedim** [typestack/class-validator#1644] opened 2022-05-10 13:36 UTC
### Description
I was just trying update my element by UPDATE and validate inputs with **class-validator**. The problem is even though I'm sure that validation is a match with my body.

My request looks like this.
```js
{
     articleNumber: '293213'
     prices: [{ price: 100, fromQuantity: 1, toQuantity: 10 }]
}
```

What I got.
```js
{
     articleNumber: '293213'
     prices: [ {} ]
}
```

So article is updating but my pricing is also updating wrongly.

**Minimal code-snippet showcasing the problem**
 

My dto.ts file
```ts

export class CreateProductlineDto {
  @IsNotEmpty()
  @IsString()
  articleNumber: string;

  @IsOptional()
  @IsArray()
  // THE PROBLEM IS HERE !!!!
  // IF I REMOVE THE @ValidateNested() I GET INPUTS OF REQUEST.BODY
  // BUT I DONT GET THE VALIDATION ERRORS EG. YOU CAN GIVE NEGATIVE NUMBER !!!
  @ValidateNested({ each: true })
  @Type(() => Price)
  prices?: Price[];
```
If i remove `ValidateNested()` i see my request like how it is (`prices: [{ price: 100, fromQuantity: 1, toQuantity: 10 }]`) in otherwise its seems like `prices: [ {} ]`

But then I can't validate inputs with the Price item

```ts
export class Price {
  @IsNumber()
  @IsPositive()
  fromQuantity: number;

  @IsOptional()
  @IsNumber()
  @IsPositive()
  toQuantity?: number;

  @IsNumber()
  @IsPositive()
  price: number;
}
```

So they are not working if I remove `ValidateNested()`.

### Expected behavior
My inputs will validate by chosen properties and it shouldn't be `prices: [ {} ]` because my database also saves like that, so it's going to be null.

### Actual behavior

Even I send body like this `prices: [{ price: 100, fromQuantity: 1, toQuantity: 10 }]` after validating its saving as `prices: [ {} ]` to database. but If I remove `ValidateNested()` its saving with true types but of course without validation.

**Comment by braaar** [comment] 2022-11-19 15:10
Are you contructing an instance of Price? ValidateNested expects a class instance, not a plain object.

**Comment by NoNameProvided** [comment] 2022-11-20 13:23
The issue doesn't contain a minimal, runnable reproduction example. Closing this as invalid for now.

If the issue still persists, please provide a minimal **runnable** example where we can see what the problem is. Without that, we can only guess how you use the library.

**Closed as completed by NoNameProvided** 2022-11-20 13:23 UTC
Labels: type: fix, status: invalid / expired
