### ISSUE TITLE
feature: export ValidationMetadata and ValidationMetadataArgs

### ISSUE THREAD

**Issue by code-farmer-i** [typestack/class-validator#2248] opened 2023-09-20 02:55 UTC
I want to implement an IsOptionalNotNull decorator, currently this is how it is done

```ts
import {
  ValidationOptions,
  getMetadataStorage,
  ValidationTypes,
} from 'class-validator';
// @ts-ignore
import { ValidationMetadata } from 'class-validator/cjs/metadata/ValidationMetadata';
import { ValidationMetadataArgs } from 'class-validator/types/metadata/ValidationMetadataArgs';

export function IsOptionalNotNull(
  validationOptions?: ValidationOptions
): PropertyDecorator {
  return function (object, propertyName): void {
    const args: ValidationMetadataArgs = {
      type: ValidationTypes.CONDITIONAL_VALIDATION,
      target: object.constructor,
      propertyName: propertyName,
      constraints: [
        (object: any): boolean => {
          return object[propertyName] !== undefined;
        },
      ],
      validationOptions: validationOptions,
    };
    getMetadataStorage().addValidationMetadata(new ValidationMetadata(args));
  };
}

```

I hope class-validator can export ValidationMetadata and ValidationMetadataArgs in the entry file

```ts
import {
  ValidationMetadata,
  ValidationMetadataArgs
} from 'class-validator';

```

**Comment by braaar** [comment] 2023-09-20 11:38
Thanks for the issue, but I would say this is a duplicate of #944 so this can be tracked there, instead.

**Closed as not planned by braaar** 2023-09-20 11:38 UTC
Labels: type: feature, status: duplicate
