### ISSUE TITLE
[Feature Request] @IfValid(propertyName)

### ISSUE THREAD

**Issue by oleersoy** [typestack/class-validator#218] opened 2018-06-07 21:43 UTC
In the below case the sales price validates only if the purchase price is valid.  In other words the second validation depends on another property on the model, hence we want to make sure that it is valid before validating the dependent:

```
@IsPositive
@IsDefined
purchasePrice: Number;

@IfValid('purchasePrice')
@IsGreaterThan('purchasePrice')
@IsPositive
@IsDefined
salesPrice: Number
```

If the `validate` method supports the signature `validate(object:any, propertyName: string)` then I think something like `@ValidateIf(o => validate(o, 'otherProperty'))`.  So for this example it would be:
```
@IsPositive
@IsDefined
purchasePrice: Number;

@IfValid(o => validate(o, 'purchasePrice')))
@IsGreaterThan('purchasePrice')
@IsPositive
@IsDefined
salesPrice: Number
```

**Comment by oleersoy** [comment] 2018-06-07 22:06
Also just curious does the `validate()` method maintain the order of the decorators when validating the property?  For example as shown above is `@IsDefined` always guaranteed to execute before `@IsPositive`?

I noticed that the `IsLongerThan` example in the documentation is pretty close to this, except that in this case all the validators attached to a property would have to be invoked in order to satisfy the constraint.

**Comment by oleersoy** [comment] 2018-06-12 14:03
Personal note: Fix spelling mistakes in the comments in this file:
https://github.com/typestack/class-validator/blob/master/src/validation/ValidationTypes.ts#L107

Also it looks like null and undefined checks can be checked in a shorter way like this:
https://stackoverflow.com/questions/28975896/is-there-a-dedicated-function-to-check-null-and-undefined-in-typescript

**Comment by oleersoy** [comment] 2018-06-14 02:06
https://github.com/typestack/class-validator/blob/master/src/register-decorator.ts

``` 
    /**
     * Target object to be validated.
     */
    target: Function;
```

Should be:

```
    /**
     * Constructor of target object being validated.
     */
    target: Function;

```

**Comment by NoNameProvided** [comment] 2018-07-19 09:37
Duplicate of #134.

**Closed** 2020-04-19 18:50 UTC
